@startuml

title __PROGETTO PROGRAMMAZIONE AD OGGETTI JAVA's Class Diagram__\n

  namespace  {
    class MavenWrapperDownloader {
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      class com.example.progetto.ProgettoApplication {
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace Spring {
        class com.example.progetto.Spring.DataCsvRow {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace Spring {
        class com.example.progetto.Spring.DataCsvRowController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace Spring {
        class com.example.progetto.Spring.DataCsvRowServices {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace Spring {
        class com.example.progetto.Spring.FilterParameter {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace Spring {
        class com.example.progetto.Spring.NumberStats {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        class com.example.progetto.csvClasses.DataCsv {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace csvRetrieve {
          class com.example.progetto.csvClasses.csvRetrieve.CsvSplitter {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace csvRetrieve {
          class com.example.progetto.csvClasses.csvRetrieve.CsvValidator {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace csvRetrieve {
          class com.example.progetto.csvClasses.csvRetrieve.GetCsvDataFromUrl {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace csvRetrieve {
          class com.example.progetto.csvClasses.csvRetrieve.GetCsvUrlFromJsonUrl {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace csvRetrieve {
          class com.example.progetto.csvClasses.csvRetrieve.ReadLineFromBufferedReader {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace dataType {
          class com.example.progetto.csvClasses.dataType.Metadata {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace dataType {
          class com.example.progetto.csvClasses.dataType.ObjArray {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace dataType {
          class com.example.progetto.csvClasses.dataType.PrintClass {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.progetto {
      namespace csvClasses {
        namespace dataType {
          class com.example.progetto.csvClasses.dataType.UrlWithDescription {
          }
        }
      }
    }
  }
  

  com.example.progetto.csvClasses.csvRetrieve.CsvSplitter o-- com.example.progetto.csvClasses.csvRetrieve.GetCsvDataFromUrl : csv
  com.example.progetto.csvClasses.csvRetrieve.GetCsvDataFromUrl o-- com.example.progetto.csvClasses.csvRetrieve.ReadLineFromBufferedReader : br


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
