@startuml

title __PROGETTO's Class Diagram__\n

    class MavenWrapperDownloader {
    }

  


    namespace om.example.progetto {
      class csvClasses.dataType.Metadata {
      }
    }

    namespace om.example.progetto {
      class com.example.progetto.ProgettoApplication {
      }
    }

    namespace ontroller {
      class controller.DataServices {
      }
    }

    namespace ontroller {
      class controller.newRestController {
      }
    }

    namespace svClasses {
      class csvClasses.csvRetrieve.CsvSplitter {
      }
    }

    namespace svClasses {
      class csvClasses.csvRetrieve.CsvValidator {
      }
    }

    namespace svClasses {
      class csvClasses.DataCsv {
      }
    }

    namespace svClasses {
      class com.example.progetto.DataCsvRow {
      }
    }

    namespace svClasses {
      class csvClasses.csvRetrieve.GetCsvDataFromUrl {
      }
    }

    namespace svClasses {
      class csvClasses.csvRetrieve.GetCsvUrlFromJsonUrl {
      }
    }

    namespace svClasses {
      class csvClasses.csvRetrieve.ReadLineFromBufferedReader {
      }
    }

    namespace svClasses {
      namespace dataType {
        class csvClasses.dataType.FloatArray {
        }
      }
    }

    namespace svClasses {
      namespace dataType {
        class csvClasses.dataType.PrintClass {
        }
      }
    }

    namespace svClasses {
      namespace dataType {
        class csvClasses.dataType.StringArray {
        }
      }
    }

  

  csvClasses.csvRetrieve.CsvSplitter o-- csvClasses.csvRetrieve.GetCsvDataFromUrl : csv
  csvClasses.csvRetrieve.GetCsvDataFromUrl o-- csvClasses.csvRetrieve.ReadLineFromBufferedReader : br


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
